version: "3.8"
services:
  redis:
    image: redis:6.0.6
    expose:
      - 6379
  server:
    build: server/
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
  haproxy:
    image: eeacms/haproxy:1.8-1.5
    depends_on:
      - server
    ports:
      - 8080:8080
      - 8081:1936
    environment:
      FRONTEND_PORT: 8080
      BACKENDS: server
      BACKENDS_PORT: 8080
      DNS_ENABLED: "True"
      HTTPCHK: GET /ping
      LOG_LEVEL: info
  client:
    stdin_open: true
    build: client/
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - /app/node_modules
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - haproxy